apiVersion: apps/v1
kind: Deployment
metadata:
  name: groceries-backend
  labels:
    app: groceries-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groceries-backend
  template:
    metadata:
      labels:
        app: groceries-backend
    spec:
      serviceAccountName: sql-ksa
      initContainers:
        - name: cloud-sql-proxy
          restartPolicy: Always
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          args:
            - "--private-ip"
            - "--structured-logs"
            - "--port=3306"
            - "georgef-sandbox:us-central1:sql-instance"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
      containers:
        - name: groceries-backend
          image: us-central1-docker.pkg.dev/georgef-sandbox/groceries/groceries-backend-cloud-sql-proxy:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "exampledb"
            - name: DB_PORT
              value: "3306"
            - name: CORS_ORIGIN
              value: "http://host.docker.internal:3000"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
