apiVersion: apps/v1
kind: Deployment
metadata:
  name: groceries-backend
  labels:
    app: groceries-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: groceries-backend
  template:
    metadata:
      labels:
        app: groceries-backend
    spec:
      serviceAccountName: sql-ksa
      containers:
        - name: groceries-backend
          image: us-central1-docker.pkg.dev/georgef-sandbox/groceries/groceries-backend-cloud-sql-proxy:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "exampledb"
            - name: DB_PORT
              value: "3306"
            - name: CORS_ORIGIN
              value: "http://host.docker.internal:3000"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          args:
            - /cloud_sql_proxy
            - -instances=georgef-sandbox:us-central1:sql-instance=tcp:3306
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
