apiVersion: v1
kind: Service
metadata:
  name: groceries-backend
  labels:
    app: groceries-backend
spec:
  type: ClusterIP
  selector:
    app: groceries-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
