apiVersion: v1
kind: Service
metadata:
  name: groceries-frontend
spec:
  type: ClusterIP
  selector:
    app: groceries-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # <-- nginx-proxy listens here
