apiVersion: apps/v1
kind: Deployment
metadata:
  name: groceries-frontend
  labels:
    app: groceries-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: groceries-frontend
  template:
    metadata:
      labels:
        app: groceries-frontend
    spec:
      containers:
        - name: groceries-frontend
          imagePullPolicy: Always
          image: us-central1-docker.pkg.dev/georgef-sandbox/groceries/frontend
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://34.118.235.3/groceries"
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
