apiVersion: v1
kind: ConfigMap
metadata:
  name: groceries-nginx-config
data:
  default.conf: |
    server {
      listen 8080;

      location / {
        proxy_pass http://localhost:80;
      }

      location /api/groceries/ {
        proxy_pass http://groceries-backend/groceries;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
