cloud-sql-proxy --port 3306 --credentials-file=./creds/mysql-key.json georgef-sandbox:us-central1:sql-instance

windows:
cloud-sql-proxy.exe --port 3306 --credentials-file=../creds/mysql-key.json georgef-sandbox:us-central1:sql-instance
cloud-sql-proxy.exe georgef-sandbox:us-central1:sql-instance --credentials-file=../creds/mysql-key.json


assign ksa + gcp sa
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#workload-identity

kubectl create sa sql-ksa
 

gcloud iam service-accounts add-iam-policy-binding cliect-sql@georgef-sandbox.iam.gserviceaccount.com \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:georgef-sandbox.svc.id.goog[dev/sql-ksa]"


  gcloud container clusters describe my-gke-cluster --zone=us-central1-a --project=georgef-sandbox \
  --format="value(workloadIdentityConfig.workloadPool)"