cloud-sql-proxy --port 3306 --credentials-file=./creds/mysql-key.json georgef-sandbox:us-central1:sql-instance

windows:
cloud-sql-proxy.exe --port 3306 --credentials-file=../creds/mysql-key.json georgef-sandbox:us-central1:sql-instance
cloud-sql-proxy.exe georgef-sandbox:us-central1:sql-instance --credentials-file=../creds/mysql-key.json


assign ksa + gcp sa
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#workload-identity

kubectl create sa sql-ksa

gcloud iam service-accounts add-iam-policy-binding \
--role="roles/iam.workloadIdentityUser" \
--member="serviceAccount:project-id.svc.id.goog[default/sql-ksa]" \
cliect-sql@project-id.iam.gserviceaccount.com
 

gcloud projects add-iam-policy-binding projects/georgef-sandbox \
--role=roles/container.clusterViewer \
--member=principal://iam.googleapis.com/projects/541704241308/locations/global/workloadIdentityPools/georgef-sandbox.svc.id.goog/subject/ns/dev/sa/sql-ksa \
--condition=None